### ISSUE TITLE
Double page requests when interacting with modals

### ISSUE THREAD

**Issue by joemasilotti** [hotwired/hotwire-native-ios#12]
In merging outstanding PRs from turbo-ios I learned that [PR #155](https://github.com/hotwired/turbo-ios/pull/155) doesn't play nicely with Turbo Navigator. It can cause screens to not render at all due to the cached visit options being out of sync. I decided to skip the merge (for now) because it was causing more issues than it fixed.

A new, and I think related, issue has popped up instead. Using the Demo app, double requests are not being made to anything related to modals.

Launching the demo app and:
1. Tapping "Load a webpage modally" requests `/new` twice
2. Submitting the form POSTs once correctly but requests `/success` twice

**Comment by olivaresf** [comment]
This should be fixed in https://github.com/hotwired/hotwire-native-ios/pull/24.

**Comment by olivaresf** [comment]
@joemasilotti could you help me review #24? I believe that should fix the issue.

**Comment by joemasilotti** [comment]
I'm still seeing the same behavior of modals and form submissions hitting twice in the demo app (and same for my Rails server):

```
Mon Oct 21 2024 11:09:00 GMT-0700 (Pacific Daylight Time) -- GET /new
Mon Oct 21 2024 11:09:00 GMT-0700 (Pacific Daylight Time) -- GET /new
Mon Oct 21 2024 11:09:01 GMT-0700 (Pacific Daylight Time) -- POST /new
Mon Oct 21 2024 11:09:01 GMT-0700 (Pacific Daylight Time) -- GET /success
Mon Oct 21 2024 11:09:01 GMT-0700 (Pacific Daylight Time) -- GET /success
```

**Comment by jayohms** [comment]
Note, this issue is due to two completely separate issues:

1. Double-requests to `/new` is due to Turbo link prefetching being initiated when tapping on the `/new` link, but prefetching results won't work across multiple `default`/`modal` `WKWebView` sessions. To address this, we plan to disable prefetching in the native libraries, since link taps was not an expected use of prefetching anyway (as opposed to mouse hover events).
2. Double-requests to `/success` is due to the issue outlined in this PR: #60

**Comment by jayohms** [comment]
Both issues were resolved with:

- https://github.com/hotwired/hotwire-native-ios/pull/60
- https://github.com/hotwired/hotwire-native-ios/pull/62
